config/routes.rb
Jewelleryboxbg::Application.routes.draw do
  

  

  devise_for :admins

  resources :products do
    resources :pictures
    resources :order_forms
  end

  as :admin do
    get '/admin', to: 'devise/sessions#new', as: :login
  end

  root to: 'products#featured'
  match '/featured' => 'products#featured'
  match '/faq-en' => 'products#faq', :as => :faq
  match '/faq-bg' => 'products#faq_bg', :as => :faq_bg
  match '/featured2' => 'order_forms#featured'
  match '/orders' => 'order_forms#index'
  match '/orders/shipped' => 'order_forms#shipped', :as => :shipped

end

app/controllers/order_forms_controller.rb
class OrderFormsController < ApplicationController
	before_filter :authenticate_admin!, only: [:index]
	before_filter :find_product, only: [:show, :new, :create]
	before_filter :find_order, only: [:shipped, :show]



	def index
		#@order = @product.order_forms.all
		@order = OrderForm.all
	end

	def show 

	end

	def new
		@order = OrderForm.new
		

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @order }
	    end
	end

	def create
		@order = @product.order_forms.new(params[:order_form])

		respond_to do |format|
			if @order.save
				format.html { redirect_to root_path, notice: 'Your order was successfull! Feel free to contact us for its status at: office@jewellerybox.bg' }
			else
				format.html { render action: "new" }
			end
		end
	end

	def shipped
		#@product = Product.find(params[:product_id])
		#@order = @product.order_form.find(params[:order_form_id])
		#@order = OrderForm.find(params[:_id])
		#@order = @product.order_forms.find_by_id(params[:id])
		#@product = Product.find_by_id(params[:product_id])
		#@order = @product.orders.find(params[:order_form])
		#@product = Product.find_by_id(params[:product_id])
		@order = @product.order_forms.find(params[:id])
		@order.shipped = true
		@order.save
		redirect_to orders_url
	end

	def not_shipped
		@order = @product.order_forms.find(params[:id])
		@order.shipped = false
		@order.save
		redirect_to orders_url
	end



	private

	def find_order
		#@order = @product.order_forms.find_by_id(params[:id])
		#@order = @product.order_forms.find_by_id(params[:order_form_id])
	end

	def find_product
		@product = Product.find(params[:product_id])
		#@product = Product.find_by_id(params[:product_id])
	end


end

app/helpers/order_forms_helper.rb
module OrderFormsHelper
	def total_order(order)
		if order.product.discount
			order.quantity * (order.product.price - order.product.discount)
		else
			order.quantity * order.product.price
		end
	end
end

app/views/order_forms/_form.html.erb
<%= simple_form_for([@product, @order], html: { class: ''}) do |f| %>

<div class="row-fluid">

	<div class="span12">
		<%= f.input :name, input_html: { class: 'input-xxlarge' }, label: 'Full name' %>
	</div>
	<div class="span6">
		<%= f.input :city, placeholder: '(Sofia / София)', input_html: { class: 'input-xlarge' } %>
	</div>
	<div class="span4">
		<%= f.input :phone, input_html: { class: '' } %>
	</div>
	
	<div class="span12">
	<%= f.input :address_type, inline_label: 'Yes, Ship to EKONT office', label: 'Shipping to a EKONT office?' %>
	<%= f.input :address, input_html: { class: 'input-xxlarge' }, placeholder: '(Улица/Булевард, №, бл., вх., ет., ап.)' %>
	<%= f.input :message, label: 'Message, if any', input_html: { class: 'input-xxlarge', rows: 4 }, placeholder: '(Size, color, etc...)' %>
	</div>
	<div class="span6">
		<%= f.input :quantity, label: 'How many would you like to order?', input_html: { class: 'input-xlarge' } %>
	</div>
	<div class="span4">
		<%= f.input :email, label: 'Email (optional)' %>
	</div>

</div>

<div>
	<%= f.button :submit, data: { confirm: "Confirm Order! After confirming you will be contacted by EKONT Express to receive your order. Thank you!" }, class: 'btn btn-primary btn-large pull-right' %>
</div>
<% end %>

app/views/order_forms/featured.html.erb
<script>
    $(document).ready(function(){$('.carousel').carousel();});
</script>

<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    
    <% if Product.exists?(3) %>
      <% @products.last(3).each do |product| %>
        <% if product == @products[-3] %>
            <div id="add-class-to-carousel" class="item active">
        <% else %>
            <div id="add-class-to-carousel" class="item">
        <% end %>
              <div id="links">
                <div class="container-fluid" id="show_product">
                  <div class="row-fluid">
                    <section class="span12">
                      <h1>
                        <span class="product_title span11"><%= product.title %></span>
                      </h1>
                        <div class="span12"><p><hr /></p></div>
                    </section>
                    <section class="product_image span5">
                      <% product.pictures.each do |picture| %>
                        <a href="<%= picture.asset.url %>">
                          <% if picture == Picture.first %>
                            <img src="<%= picture.asset.url(:medium) %>"
                          <% end %>
                        </a>
                      <% end %>
                    </section>
                    <section class="info_right span6">
                      <section class="product_description offset3 span9">
                      <p><%= product.description %></p>
                      </section>
                      <section class="offset3 span9">
                        <br />
                        <p><em>
                          <span class="product_item_id">Product ID: <%= product.item_id %></span><br />
                          <span class="product_quantity">Quantity: <%= product.quantity %> left</span><br />
                          <span class="product_discount">Discount: <%= product.discount %> BGN</span>
                        </em></p><br />
                      </section>
                      <section class="product_price_class offset1 span11">
                        <p>Price class: <%= product.price_class %></p>
                      </section>
                      <section class="product_warranty product_guarantee offset1 span11">
                        <p>Warranty: <% if product.warranty? %><%= product.warranty %><% else %><em>No warranty available</em><% end %><br /><% if product.guarantee? %>Guarantee: <%= product.guarantee %><% end %></p>
                      </section>
                      <section class="product_order span12">
                        <a href="#<%= product.title.gsub(/\s+/, "") %>" role="button" class="btn btn-success pull-right" data-toggle="modal" style="z-inxed: 99;">Order now!</a>
                      </section>
                    </section>

                  </div>
                </div>
              </div>
              <div class="span12">
                
              </div>
          </div>
      <% end %>
    <% end %>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>


<% @products.each do |product| %>
<div id="<%= product.title.gsub(/\s+/, "") %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3><span class="product_title"><%= product.title %></span></h3>
    </div>
    <div class="modal-body">
        <div class="container-fluid" id="show_product">
          <div class="row-fluid">
            <section class="product_image span6">
              <%= image_tag product.gallery.url(:medium) %>
            </section>
            <section class="info_right span6">
              <section class="product_description offset3 span9">
              <p><%= product.description %></p>
              </section>
            </section>
            <select class="span12">
              <% product.order_forms.each do |order| %>
                
              <% end %>
            </select>
          </div>
        </div>
    </div>
</div>
<% end %>


<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
  <% @products.each do |product| %>
  <% product.pictures.each do |picture| %>
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
  <% end %>
  <% end %>
</div>

<script>
                window.onload = function () {
              document.getElementById('links').onclick = function (event) {
                  event = event || window.event;
                  var target = event.target || event.srcElement,
                      link = target.src ? target.parentNode : target,
                      options = {index: link, event: event},
                      links = this.getElementsByTagName('a');
                  blueimp.Gallery(links, options);
              };
            };
              </script>
              <!--  -->

app/views/order_forms/index.html.erb
<h2>All Orders</h2>
<hr />

<% @order.each do |order| %>
	<div id="orders">
			<h3><%= order.id %># '<%= order.name %>' has ordered <%= order.quantity %> x '<%= order.product.title %>' | id: <%= order.product_id %></h3>
			<h4>Ship to: <%= order.city %>, <% if order.address_type == true %>Ekont office: <% else %>Home Address: <% end %><%= order.address %></h4>
			<h4>TOTAL: 
				<%= total_order(order) %> BGN (without shipping costs)
			</h4>
			<br />
			<p>Additional Info:</p>
			<p><% if !order.message.blank? %>Message: <em><%= order.message %></em> <% else %>No message<% end %></p>
			<p>Price per item: <% if order.product.discount %><%= order.product.price - order.product.discount %> BGN with discount.<% else %> <%= order.product.price %> BGN.<% end %> | Quantity ordered: <%= order.quantity %></p>
			<br />
			<p>Phone: <%= order.phone %></p>
			<p><% if !order.email.blank? %>Email: <%= order.email %><% else %>No email<% end %></p>

			<p><a href="#" class="btn btn-success">Yes I shipped <%= order.quantity %> x <%= order.product.title %> to <%= order.name %> for <%= total_order(order) %> BGN</a></p>
			<%= link_to "Shipped", shipped_path(order.id) %>

	</div>
	<hr />
<% end %>

app/views/order_forms/new.html.erb
<h2 class="text-center">To order <%= @product.title %>,</h2>
<h4 class="text-center">fill in the form below in any language and submit it. We will handle the rest.</h4>
<hr />

	<div class="container-fluid" id="show_product">
	  <div class="row-fluid">
	    <section class="product_image span6">
	      <% if @product.pictures.exists? %>
              <div id="links">
                <% @product.pictures.order('updated_at DESC').each do |picture| %>
                  <a href="<%= picture.asset.url %>" id="gallery">
                      <% if picture == @product.pictures.last %>
                        <img src="<%= picture.asset.url(:medium) %>">
                      <% end %>
                  </a>
                <% end %>
                <p class="text-center">Click image for more.</p>
              </div>
            <% else %>
		  	<%= image_tag @product.gallery.url(:medium) %>
		  <% end %>
	    </section>
	    <section class="info_right span6">
	      <section class="product_description offset3 span9">
	      <p><%= @product.description %></p>
	      </section>
	      <section class="offset3 span9">
	        <br />
	        <p><em>
	          <span class="product_item_id">Product ID: <%= @product.item_id %></span><br />
	          <span class="product_quantity">Quantity: <%= @product.quantity %> left</span><br />
	          <span class="product_discount">Discount: <%= @product.discount %> BGN</span>
	        </em></p><br />
	      </section>
	      <section class="product_price_class offset1 span11">
	        <p>Price class: <%= @product.price_class %></p>
	      </section>
	      <section class="product_warranty product_guarantee offset1 span11">
	        <p>Warranty: <% if @product.warranty? %><%= @product.warranty %><% else %><em>No warranty available</em><% end %><br /><% if @product.guarantee? %>Guarantee: <%= @product.guarantee %><% end %></p>
	      </section>
	    </section>
	    <hr />
	    <div class="span12">
			<h3 class="text-center">Order now</h3>
			<%= render 'form' %>
			<p class="final_price_text">TOTAL:
			<% if @product.discount %>
				<span class="final_price"><%= @product.price - @product.discount %> BGN</span> (per ITEM)</p>
				<p>with <%= @product.discount %> BGN discount!</p>
			<% else %>
				<span class="final_price_text"><span class="final_price"><%= @product.price %> BGN</span> (per ITEM)</span></p>
			<% end %>
			<%= link_to 'Cancel', root_url, class: 'btn pull-right' %>
	    </div>

      </div>
	</div>

	


	




<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>