config/routes.rb
Jewelleryboxbg::Application.routes.draw do
  

  

  devise_for :admins

  resources :products do
    resources :pictures
    resources :order_forms
  end

  as :admin do
    get '/admin', to: 'devise/sessions#new', as: :login
  end

  root to: 'products#featured'
  match '/featured' => 'products#featured'
  match '/faq-en' => 'products#faq', :as => :faq
  match '/faq-bg' => 'products#faq_bg', :as => :faq_bg
  match '/featured2' => 'order_forms#featured'
  match '/orders' => 'order_forms#index'
  match '/orders/shipped' => 'order_forms#shipped', :as => :shipped

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :product
  attr_accessible :asset

  has_attached_file :asset, styles: {
  	large: "800x800>", medium: "300x200>", small: "260x180>", thumb: "80x80#"
  }

  validates_attachment_presence :asset
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_admin!, except: [:index]
  before_filter :find_product
  before_filter :find_picture, only: [:edit, :update, :show, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    #@pictures = Picture.all
    @pictures = @product.pictures.order('updated_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    #@picture = Picture.find(params[:id])
    @picture = @product.pictures.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    #@picture = Picture.new
    @picture = @product.pictures.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    #@picture = Picture.find(params[:id])
    #@picture = @product.picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    #@picture = Picture.new(params[:picture])
    @picture = @product.pictures.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to product_pictures_path(@product), notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    #@picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to product_pictures_path(@product), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to product_pictures_path(@product) }
      format.json { head :no_content }
    end
  end



  private

  def find_picture
    @picture = @product.pictures.find(params[:id])
  end

  def find_product
    @product = Product.find(params[:product_id])
  end


end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= simple_form_for([@product, @picture], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :asset, as: :file %>
  </div>

  <hr />
  <div>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', product_picture_path(@product, @picture) %> |
<%= link_to 'Back', product_pictures_path(@product) %>

app/views/pictures/index.html.erb
<h1>Listing pictures for <%= @product.title %> #<%= @product.item_id %> <%= link_to 'New Picture', new_product_picture_path(@product), class: 'btn btn-primary' %></h1>

<% @pictures.each do |picture| %>
  <ul class="thumbnails">
    <li class="span4">
      <div class="thumbnail">
        <%= image_tag(picture.asset.url) %>
      </div>
    </li>
  </ul>
  <%= link_to 'View full size', product_picture_path(@product, picture) %> |
  <%= link_to 'Edit', edit_product_picture_path(@product, picture) %> |
  <%= link_to "Delete", product_picture_path(@product, picture), method: :delete, data: { confirm: "Are you sure?"} %>
  <hr />
<% end %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', product_pictures_path(@product) %>

app/views/pictures/show.html.erb
<%= image_tag(@picture.asset.url(:large), class: 'img-polariod') %>

<p>
  <b>Product:</b>
  <%= @picture.product %>
</p>

<%= link_to 'Back', product_pictures_path(@product) %> |
<%= link_to 'Edit', edit_product_picture_path(@product, @picture) %> |
<%= link_to "Delete", product_picture_path(@product, @picture), method: :delete, data: { confirm: "Are you sure?" } %>