config/routes.rb
Jewelleryboxbg::Application.routes.draw do
  

  

  devise_for :admins

  resources :products do
    resources :pictures
    resources :order_forms
  end

  as :admin do
    get '/admin', to: 'devise/sessions#new', as: :login
  end

  root to: 'products#featured'
  match '/featured' => 'products#featured'
  match '/faq-en' => 'products#faq', :as => :faq
  match '/faq-bg' => 'products#faq_bg', :as => :faq_bg
  match '/featured2' => 'order_forms#featured'
  match '/orders' => 'order_forms#index'
  match '/orders/shipped' => 'order_forms#shipped', :as => :shipped

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pictures
  has_many :order_forms
  attr_accessible :description, :discount, :guarantee, :item_id, :price, :price_class, :quantity, :title, :warranty, :gallery
  has_attached_file :gallery, :styles => { :medium => "200x200>", :thumb => "125x125>" }, :default_url => "/images/:style/logo.png"

  validates :title, presence: true
  validates :description, presence: true
  validates :item_id, presence: true, uniqueness: true
  validates :price, presence: true
  validates :price_class, presence: true
  validates :quantity, presence: true
  validates :gallery, attachment_presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_product
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def featured
    @products = Product.all


    respond_to do |format|
      format.html # featured.html.erb
      format.json { render json: @products }
    end
  end

  def faq
    
  end

  def faq_bg

  end

  # GET /products/1
  # GET /products/1.json
  def show
    #@product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    #@product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def find_product
    @product = Product.find_by_id(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :multipart => true, class: "form-horizontal" } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title, input_html: { class: 'input-xxlarge' }, placeholder: '(Insert EPIC NAME here)' %>
  <%= f.input :description, input_html: { class: 'input-xxlarge', rows: 4 }, placeholder: '(a rly shrt dscrptn)' %>
  <%= f.input :item_id, placeholder: '(must be unique)' %>
  <%= f.input :discount, placeholder: '(optional)' %>
  <%= f.input :price, placeholder: '25 (without BGN)' %>
  <%= f.input :price_class, placeholder: 'A (0-15 A, 15-30 AA, 30-50 AAA)', hint: 'Calculate without the included discount' %>
  <%= f.input :quantity, placeholder: '(12)', hint: 'Update with the EDIT buttons' %>
  <%= f.input :warranty, placeholder: '(30 day full coverage)' %>
  <%= f.input :guarantee, placeholder: '(30 day money back)' %>

  <div class="upload_field">
    <%= f.input :gallery, hint: 'Upload pictures with transparent backgrounds!' %>
  </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<br />

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/featured.html.erb
<script>
    $(document).ready(function(){$('.carousel').carousel();});
</script>

<h2 class="text-center">Welcome to Jewellerybox,</h2>
<h4 class="text-center">beautiful, sophisticated silver jewellery, each week.</h4>
<br />

<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    
    <% if Product.exists?(3) %>
      <% @products.last(3).each do |product| %>
        <% if product == @products[-3] %>
            <div id="add-class-to-carousel" class="item active">
        <% else %>
            <div id="add-class-to-carousel" class="item">
        <% end %>
                <div class="container-fluid" id="show_product">
                  <div class="row-fluid">
                    <section class="span12">
                      <h1>
                        <span class="product_title span11"><%= product.title %></span>
                      </h1>
                        <div class="span12"><p><hr /></p></div>
                    </section>
                    <section class="product_image span5">
                      <% if product.pictures.exists? %>
                          <% product.pictures.order('updated_at DESC').each do |picture| %>
                            <a href="<%= product_path(product) %>">
                                <% if picture == product.pictures.last %>
                                  <img src="<%= picture.asset.url(:medium) %>">
                                <% end %>
                            </a>
                          <% end %>
                      <% else %>
                        <%= link_to image_tag(product.gallery.url(:medium)), product_path(product) %>
                      <% end %>
                    </section>
                    <section class="info_right span6">
                      <section class="product_description offset3 span9">
                      <p><%= product.description %></p>
                      </section>
                      <section class="offset3 span9">
                        <br />
                        <p><em>
                          <span class="product_item_id">Product ID: <%= product.item_id %></span><br />
                          <span class="product_quantity">Quantity: <%= product.quantity %> left</span><br />
                          <span class="product_discount">Discount: <%= product.discount %> BGN</span>
                        </em></p><br />
                      </section>
                      <section class="product_price_class offset1 span11">
                        <p>Price class: <%= product.price_class %></p>
                      </section>
                      <section class="product_warranty product_guarantee offset1 span11">
                        <p>Warranty: <% if product.warranty? %><%= product.warranty %><% else %><em>No warranty available</em><% end %><br /><% if product.guarantee? %>Guarantee: <%= product.guarantee %><% end %></p>
                      </section>
                      <section class="product_order span12">
                        <% if false %>
                        <a href="#<%= product.title.gsub(/\s+/, "") %>" role="button" class="btn btn-success pull-right" data-toggle="modal" style="z-inxed: 99;">Order now!</a>
                        <% end %>

                        <%= link_to "How to order?", faq_path, class: 'btn btn-info pull-right' %>
                        <%= link_to "Order now!", new_product_order_form_path(product), class: 'btn btn-success pull-right' %>

                      </section>
                    </section>

                  </div>
                </div>
          </div>
      <% end %>
    <% end %>
  </div>
  <div class="fb-like" data-href="http://www.facebook.com/jewellerybox.bg" data-width="300" data-layout="button_count" data-show-faces="false" data-send="true"></div>
  <p class="text-center"><%= link_to image_tag("btn-facebook.png") + " /jewellerybox.bg", "http://www.facebook.com/jewellerybox.bg", class: 'btn btn-facebook' %></p>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/products/index.html.erb
<h2 class="text-center">Browse our catalog,</h2>
<h4 class="text-center">the whole collection of precious silver accessories.</h4>
<ul id="products-list" class="row-fluid">
  <% @products.each do |product| %>
            <li id="product-thumb" class="product">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <% if product.pictures.exists? %>
                                <% product.pictures.order('updated_at DESC').each do |picture| %>
                                  <a href="<%= product_path(product) %>">
                                      <% if picture == product.pictures.last %>
                                        <img src="<%= picture.asset.url(:thumb) %>">
                                      <% end %>
                                  </a>
                                <% end %>
                            <% else %>
                            <a href="<%= product_path(product) %>" role="button" data-toggle="modal"><%= image_tag product.gallery.url(:thumb) %></a>
                            <% end %>
                            <p><em><span class="product_price_class_thumb">Class: <%= product.price_class %></span></em></p>
                        </div>
                        <div class="span8">
                            <h3><a href="#<%= product.title.gsub(/\s+/, "") %>" role="button" data-toggle="modal" class="index_product_title"><%= product.title %></a></h3>
                            <p><em><%= truncate(product.description, length: 60) %></em></p>
                        </div>
                        <ul class="span12 admin">
                            <% if admin_signed_in? %>
                                <li><%= link_to 'Show', product %></li>
                                <li><%= link_to 'Edit', edit_product_path(product) %></li>
                                <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                                <li><%= link_to 'Gallery', product_pictures_path(product), class: 'btn btn-primary' %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </li>

    <% end %>
</ul>

<% @products.each do |product| %>
<div id="<%= product.title.gsub(/\s+/, "") %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3><span class="product_title"><%= product.title %></span></h3>
    </div>

    <div class="modal-body">
        <div class="container-fluid" id="show_product">
          <div class="row-fluid">
            <section class="product_image span6">
              <% if product.pictures.exists? %>
                  <% product.pictures.order('updated_at DESC').each do |picture| %>
                    <a href="<%= product_path(product) %>">
                        <% if picture == product.pictures.last %>
                          <img src="<%= picture.asset.url(:medium) %>">
                        <% end %>
                    </a>
                  <% end %>
              <% else %>
                  <%= link_to image_tag(product.gallery.url(:medium)), product_path(product) %>
              <% end %>
            </section>
            <section class="info_right span6">
              <section class="product_description offset3 span9">
              <p><%= product.description %></p>
              </section>
              <section class="offset3 span9">
                <br />
                <p><em>
                  <span class="product_item_id">Product ID: <%= product.item_id %></span><br />
                  <span class="product_quantity">Quantity: <%= product.quantity %> left</span><br />
                  <span class="product_discount">Discount: <%= product.discount %> BGN</span>
                </em></p><br />
              </section>
              <section class="product_price_class offset1 span11">
                <p>Price class: <%= product.price_class %></p>
              </section>
              <section class="product_warranty product_guarantee offset1 span11">
                <p>Warranty: <% if product.warranty? %><%= product.warranty %><% else %><em>No warranty available</em><% end %><br /><% if product.guarantee? %>Guarantee: <%= product.guarantee %><% end %></p>
              </section>
            </section>
          </div>
        </div>
    </div>
    <div class="modal-footer">
        <a class="btn pull-right" data-dismiss="modal" aria-hidden="true">Back</a>
        <%= link_to "Order now!", new_product_order_form_path(product), class: "btn btn-success" %>
        <%= link_to "How to order?", faq_path, class: 'btn btn-info pull-right' %>
        
        <% if admin_signed_in? && @product %>
            <%= link_to 'Edit', edit_product_path(@product) %>
        <% end %>
    </div>
</div>
<% end %>

app/views/products/index2.html.erb
<div class="tab-content">

    <!-- THIS IS THE INDEX PAGE -->

    <div class="tab-pane" id="products-index">
        <h1>Welcome to our catalog!</h1>
        <ul id="products-list" class="row-fluid">
          <% @products.each do |product| %>
                    <li id="product-thumb" class="product">
                        <div class="span6">
                            <div class="row-fluid">
                                <div class="span4">
                                    <a href="#<%= product.title.gsub(/\s+/, "") %>" role="button" data-toggle="modal"><%= image_tag product.gallery.url(:thumb) %></a>
                                          <div id="links">
                                            <% product.pictures.each do |picture| %>
                                                  <a href="<%= picture.asset.url %>">
                                                      <% if picture == Picture.first %>
                                                        <img src="<%= picture.asset.url(:thumb) %>">
                                                      <% end %>
                                                  </a>
                                            <% end %>
                                        </div>
                                        <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
                                          <% product.pictures.each do |picture| %>
                                            <div class="slides"></div>
                                            <h3 class="title"></h3>
                                            <a class="prev">‹</a>
                                            <a class="next">›</a>
                                            <a class="close">×</a>
                                            <a class="play-pause"></a>
                                            <ol class="indicator"></ol>
                                          <% end %>
                                        </div>
                                    <p><em><span class="product_price_class_thumb">Class: <%= product.price_class %></span></em></p>
                                </div>
                                <div class="span8">
                                    <h3><a href="#<%= product.title.gsub(/\s+/, "") %>" role="button" data-toggle="modal"><%= product.title %></a></h3>
                                    <p><em><%= truncate(product.description, length: 60) %></em></p>
                                </div>
                                <ul class="span12 admin">
                                    <% if admin_signed_in? %>
                                        <li><%= link_to 'Show', product %></li>
                                        <li><%= link_to 'Edit', edit_product_path(product) %></li>
                                        <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                                        <li><%= link_to 'New Picture', new_product_picture_path(product), class: 'btn btn-primary' %></li>
                                    <% end %>
                                </ul>
                            </div>
                        </div>
                    </li>

            <% end %>
        </ul>
    </div>

<!-- THIS IS THE FEATURED PAGE WITH DETAILED DESCRIPTIONS -->

    <div class="tab-pane active" id="featured-index">
        <!-- FEATURED PAGE WITH CAROUSEL -->
        <!-- the script starts the carousel on load due to the element nested in a tab -->
        <script>
            $(document).ready(function(){$('.carousel').carousel();});
        </script>

        <div id="myCarousel" class="carousel slide">
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>
          <!-- Carousel items -->
          <div class="carousel-inner">
            <% if Product.exists?(3) %>
            <% @products.last(3).each do |product| %>
            <% if product == @products[-3] %>
                <div id="add-class-to-carousel" class="item active">
            <% else %>
                <div id="add-class-to-carousel" class="item">
            <% end %>
                <a href="#<%= product.title.gsub(/\s+/, "") %>" role="button" data-toggle="modal">
                <div class="container-fluid" id="show_product">
                  <div class="row-fluid">
                    <section class="span12">
                      <h1>
                        <span class="product_title span11"><%= product.title %></span>
                      </h1>
                        <div class="span12"><p><hr /></p></div>
                    </section>
                    <section class="product_image span5">
                        <%= image_tag product.gallery.url(:medium) %>
                    </section>
                    <section class="info_right span6">
                      <section class="product_description offset3 span9">
                      <p><%= product.description %></p>
                      </section>
                      <section class="offset3 span9">
                        <br />
                        <p><em>
                          <span class="product_item_id">Product ID: <%= product.item_id %></span><br />
                          <span class="product_quantity">Quantity: <%= product.quantity %> left</span><br />
                          <span class="product_discount">Discount: <%= product.discount %> BGN</span>
                        </em></p><br />
                      </section>
                      <section class="product_price_class offset1 span11">
                        <p>Price class: <%= product.price_class %></p>
                      </section>
                      <section class="product_warranty product_guarantee offset1 span11">
                        <p>Warranty: <% if product.warranty? %><%= product.warranty %><% else %><em>No warranty available</em><% end %><br /><% if product.guarantee? %>Guarantee: <%= product.guarantee %><% end %></p>
                      </section>
                    </section>

                  </div>
                </div>
                </a>

            </div>
            <% end %>
            <% end %>
          </div>
          <!-- Carousel nav -->
          <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
          <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
        </div>


    </div>


<!-- THIS IS THE PREVIEW MODAL -->

<% @products.each do |product| %>
<div id="<%= product.title.gsub(/\s+/, "") %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3><span class="product_title"><%= product.title %></span></h3>
    </div>

    <div class="modal-body">
        <div class="container-fluid" id="show_product">
          <div class="row-fluid">
            <section class="product_image span6">
              <%= image_tag product.gallery.url(:medium) %>
            </section>
            <section class="info_right span6">
              <section class="product_description offset3 span9">
              <p><%= product.description %></p>
              </section>
              <section class="offset3 span9">
                <br />
                <p><em>
                  <span class="product_item_id">Product ID: <%= product.item_id %></span><br />
                  <span class="product_quantity">Quantity: <%= product.quantity %> left</span><br />
                  <span class="product_discount">Discount: <%= product.discount %> BGN</span>
                </em></p><br />
              </section>
              <section class="product_price_class offset1 span11">
                <p>Price class: <%= product.price_class %></p>
              </section>
              <section class="product_warranty product_guarantee offset1 span11">
                <p>Warranty: <%= product.warranty %><br />Guarantee: <%= product.guarantee %></p>
              </section>
            </section>
          </div>
        </div>
    </div>
    <div class="modal-footer">
        <%= link_to "See more and order", new_product_order_form_path(product), class: "btn btn-success" %>
        <a href="#faq-index" class="btn btn-info" data-toggle="tab" data-dismiss="modal" aria-hidden="true">How to order?</a>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Back</button>
        <% if admin_signed_in? && @product %>
            <%= link_to 'Edit', edit_product_path(@product) %>
        <% end %>
    </div>
</div>
<% end %>

    <!-- THIS IS THE FAQ PAGE -->

    <div class="tab-pane" id="faq-index">
        <div class="accordion" id="accordion2">
          
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                <h3>How to order?</h3>
              </a>
            </div>
            <div id="collapseOne" class="accordion-body collapse in">
              <div class="accordion-inner">
                <p>To order you must simply send an email to office@jewellerybox.bg with the following information:</p>
                <ol>
                    <li>The name of the product you want to purchase</li>
                    <li>The ID of that same item</li>
                    <li>The quantity you want</li>
                    <li>Your name and shipping address</li>
                </ol>
                <p>Thats all! Good luck</p>
              </div>
            </div>
          </div>

          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                <h4>What is included in the package?</h4>
              </a>
            </div>
            <div id="collapseTwo" class="accordion-body collapse">
              <div class="accordion-inner">
                <p>The package includes:</p>
                <ol>
                    <li>The product you ordered</li>
                    <li>A jewellery box</li>
                    <li>A jewellery bag (optional)</li>
                    <li>A cleaning cloth (optional)</li>
                    <li>A warranty card (optional)</li>
                </ol>
              </div>
            </div>
          </div>

        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                    <h4>Can I order as a Gift?</h4>
                </a>
            </div>
            <div id="collapseThree" class="accordion-body collapse">
                <div class="accordion-inner">
                    <p>You can order as a gift and include the following extras:<p>
                    <ol>
                        <li>Rose paddles</li>
                        <li>Wish card</li>
                    </ol>
                </div>
            </div>
        </div>

          <!-- End of Accordion -->
        </div>
    </div>



</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
  <h1 class="text-center"><%= @product.title %></h1>
  <div class="container-fluid" id="show_product">
    <div class="row-fluid">
      <section class="product_image span6">
        <% if @product.pictures.exists? %>
              <div id="links">
                <% @product.pictures.order('updated_at DESC').each do |picture| %>
                  <a href="<%= picture.asset.url %>" id="gallery">
                      <% if picture == @product.pictures.last %>
                        <img src="<%= picture.asset.url(:medium) %>">
                      <% end %>
                  </a>
                <% end %>
                <p class="text-center">Click image for more.</p>
              </div>
            <% else %>
        <%= image_tag @product.gallery.url(:medium) %>
      <% end %>
      </section>
      <section class="info_right span6">
        <section class="product_description offset3 span9">
        <p><%= @product.description %></p>
        </section>
        <section class="offset3 span9">
          <br />
          <p><em>
            <span class="product_item_id">Product ID: <%= @product.item_id %></span><br />
            <span class="product_quantity">Quantity: <%= @product.quantity %> left</span><br />
            <span class="product_discount">Discount: <%= @product.discount %> BGN</span>
          </em></p><br />
        </section>
        <section class="product_price_class offset1 span11">
          <p>Price class: <%= @product.price_class %></p>
        </section>
        <section class="product_warranty product_guarantee offset1 span11">
          <p>Warranty: <% if @product.warranty? %><%= @product.warranty %><% else %><em>No warranty available</em><% end %><br /><% if @product.guarantee? %>Guarantee: <%= @product.guarantee %><% end %></p>
        </section>
      </section>
      <%= link_to "Order Now!", new_product_order_form_path(@product), class: 'btn btn-primary btn-large' %>
      <% if admin_signed_in? %>
      <%= link_to "Gallery", product_pictures_path(@product), class: 'btn btn-success btn-large' %>
      <% end %>
      <%= link_to "How to order?", faq_path, class: 'btn btn-info pull-right' %>
      <%= link_to "Back", products_path, class: 'btn pull-right' %>
    </div>
  </div>


<% if false %>
<div class="container-fluid" id="show_product">
  <div class="row-fluid">
    <section class="span12">
      <h1>
        <span class="product_title span11"><%= @product.title %></span>
      </h1>
        <span class="back_button span1"><%= link_to 'Back', products_path %></span>
        <div class="span12"><p><hr /></p></div>
    </section>
    <section class="product_image span5">
      <%= image_tag @product.gallery.url(:medium) %>
    </section>
    <section class="info_right span6">
      <section class="product_description offset3 span9">
      <p><%= @product.description %></p>
      </section>
      <section class="offset3 span9">
        <br />
        <p><em>
          <span class="product_item_id">Product ID: <%= @product.item_id %></span><br />
          <span class="product_quantity">Quantity: <%= @product.quantity %> left</span><br />
          <span class="product_discount">Discount: <%= @product.discount %> BGN</span>
        </em></p><br />
      </section>
      <section class="product_price_class offset1 span11">
        <p>Price class: <%= @product.price_class %></p>
      </section>
      <section class="product_warranty product_guarantee offset1 span11">
        <p>Warranty: <%= @product.warranty %><br />Guarantee: <%= @product.guarantee %></p>
      </section>
    </section>
    <div id="show-menu-bottom" class="span12">
      <div class="span4">
        <%= link_to 'Back', products_path %>
        <% if admin_signed_in? %>
          <%= link_to 'Edit', edit_product_path(@product) %>
        <% end %>
      </div>
      <div class="span4">
        <p>Order now</p>
      </div>
      <div class="span4">
        <p>How to Order?<p>
      </div>
    </div>
  </div>

  <%= link_to 'Add pictures to Gallery', product_pictures_path(@product), class: 'btn btn-primary' %>





</div>
<% end %>

<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>