config/routes.rb
Jewelleryboxbg::Application.routes.draw do
  

  

  devise_for :admins

  resources :products do
    resources :pictures
    resources :order_forms
  end

  as :admin do
    get '/admin', to: 'devise/sessions#new', as: :login
  end

  root to: 'products#featured'
  match '/featured' => 'products#featured'
  match '/faq-en' => 'products#faq', :as => :faq
  match '/faq-bg' => 'products#faq_bg', :as => :faq_bg
  match '/featured2' => 'order_forms#featured'
  match '/orders' => 'order_forms#index'
  match '/orders/shipped' => 'order_forms#shipped', :as => :shipped

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jewelleryboxbg</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="page_container">
		<div id="header" class="row-fluid">
			<div id="logo" class="span3">
				<%= link_to image_tag('logo.png'), root_path %>
			</div>
			<div id="logo-icon">
				<%= image_tag("JewelleryBoxIcon.png") %>
			</div>
			<div id="nav" class="span9">
                <ul class="menu nav nav-pills pull-right" id="myTab">
                    <li><%= link_to "Featured", root_path %></li>
                    <li><%= link_to "Catalog", products_path %></li>
                    <li><%= link_to "F.A.Q.", faq_path %></li>
                </ul>
				<% if admin_signed_in? %>
					<ul class="menu nav nav-pills pull-right">
						<li><%= link_to "logged in as " + current_admin.profile_name, edit_admin_registration_path %></li>
						<li><%= link_to "Add new Product", new_product_path %></li>
						<li><%= link_to "All Orders", orders_path %></li>
						<li><%= link_to "Log out", destroy_admin_session_path, method: :delete %></li>
					</ul>
				<% end %>
			</div>
		</div>
				<hr />
		<div id="wrapper">
			<% if flash[:notice] %>
				<div class="alert alert-info">
					<button class="close" data-dismiss="alert">x</button>
					<%= flash[:notice] %>
				</div>
			<% end %>
			<% if flash[:alert] %>
				<div class="alert alert-error">
					<button class="close" data-dismiss="alert">x</button>
					<%= flash[:alert] %>
				</div>
			<% end %>
			<%= yield %>
		</div>
	</div>
    <%= javascript_include_tag "application" %>  
    <div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=315281495284376";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>   
</body>
</html>